### ISSUE TITLE
New value type: Variant List

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent#102]
We currently allow Select Expressions to have a null selector. This is mostly useful in Terms to define facets of the term's value:

```properties
-brand-name =
    {
       *[nominative] Firefox
        [genitive] Firefox's
    }
```

The grammar defines the above syntax as:

```yml
Term
    id: Identifier
        name: "-brand-name"
    value: Pattern
        elements:
            - Placeable
                expression: SelectExpression
                    expression: null
                    variants: […]
```
Variants defined this way can be retrieved inside of Placeable with the `-term[variant name]` syntax.  The runtime checks if the term's value is a pattern with a single element: a placeable which is a selector-less select expression. If the conditions are met, the variant is retrieved successfully.

The fact that we need this complex runtime check indicates to me that we're abusing Patterns for a logic-less (no selector) store for variants.

I'd like to make the design of Variant List more explicit by making them a new value type. Grammar-wise, values of Messages, Terms and Variants could either be Patterns or Variant Lists. Value List would not be expressions. Static analysis tools can then very easily tell when Variant Lists are mis-used: they shouldn't appear in Message at all, and they should only be nested inside of other Variant Lists.

The FTL snippet above would parse as follows:

```yml
Term
    id: Identifier
        name: "-brand-name"
    value: VariantList
        variants: […]
```
